### ISSUE TITLE
Yor failing on pull request events

### ISSUE THREAD

**Issue by bclewis1** [bridgecrewio/yor-action#15]
Yor is currently failing on pull request events - logs:

```
Run bridgecrewio/yor-action@eb0d774f3f326b7fc8bd2a9a91c57ec725986c60
/usr/bin/git checkout 108/merge
error: pathspec '108/merge' did not match any file(s) known to git

/actions-runner/_work/_actions/bridgecrewio/yor-action/eb0d774f3f326b7fc8bd2a9a91c57ec725986c60/webpack:/yor-action/node_modules/@actions/exec/lib/toolrunner.js:592
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
^
Error: The process '/usr/bin/git' failed with exit code 1
    at ExecState._setResult (/actions-runner/_work/_actions/bridgecrewio/yor-action/eb0d774f3f326b7fc8bd2a9a91c57ec725986c60/webpack:/yor-action/node_modules/@actions/exec/lib/toolrunner.js:592:1)
    at ExecState.CheckComplete (/actions-runner/_work/_actions/bridgecrewio/yor-action/eb0d774f3f326b7fc8bd2a9a91c57ec725986c60/webpack:/yor-action/node_modules/@actions/exec/lib/toolrunner.js:575:1)
    at ChildProcess.<anonymous> (/actions-runner/_work/_actions/bridgecrewio/yor-action/eb0d774f3f326b7fc8bd2a9a91c57ec725986c60/webpack:/yor-action/node_modules/@actions/exec/lib/toolrunner.js:469:1)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12)
```

for context: the branch for this pull request is `DEVEX-70-add-deployment-metrics`

**Comment by toast-gear** [comment]
It's a continuation from this https://github.com/bridgecrewio/yor-action/issues/13

**Comment by nimrodkor** [comment]
Probably not :)

I'm open for a contribution on this, will probably get to this myself next week. The solution for #13 was #14
